tasks:
  - name: initialize
    before: |
      echo "🚀"
      sudo apt install libncurses5 libxkbcommon0 libtinfo5 libnss3-tools -y
      curl https://get.wasmer.io -sSfL | sh 
      source /home/gitpod/.wasmer/wasmer.sh
      sudo echo "source /home/gitpod/.wasmer/wasmer.sh" >> $HOME/.bashrc
    init: |
      echo "🚀"

ports:
  - port: 8080
    visibility: public
  - port: 9090
    visibility: public
  - port: 9999
    visibility: public

vscode:
  extensions:
    - wayou.vscode-todo-highlight
    - pkief.material-icon-theme
    - golang.go
    - grain-lang.vscode-grain
    - rust-lang.rust

